// Login Action Types
export const FETCH_LOGIN_VIEW = 'FETCH_LOGIN_VIEW';
export const FETCH_LOGIN_USERNAME = "FETCH_LOGIN_USERNAME";
export const FETCH_LOGIN_PASSWORD = "FETCH_LOGIN_PASSWORD";


//SignUp Action Types 
export const FETCH_SIGNUP_VIEW = 'FETCH_SIGNUP_VIEW';
export const FETCH_SIGNUP_FIRSTNAME = "FETCH_SIGNUP_FIRSTNAME";
export const FETCH_SIGNUP_LASTNAME = "FETCH_SIGNUP_LASTNAME";
export const FETCH_SIGNUP_EMAIL = "FETCH_SIGNUP_EMAIL";
export const FETCH_SIGNUP_PASSWORD = "FETCH_SIGNUP_PASSWORD";



//Post Action Types
export const FETCH_POST_VIEW = 'FETCH_POST_VIEW' ;